"""Verify the workbook's formulas actually compute the right answers.

Builds a SMALL workbook with the identical formula patterns (same builder code,
fewer spells and wizards), seeds Form Responses with known data, evaluates every
formula with the `formulas` library, and asserts the cases named in the plan.

Small on purpose: the real workbook is ~30k formula cells, which the evaluator
would take a very long time to chew through. The formulas are generated by the
same code, so the patterns under test are the shipped patterns.
"""
import os
import re
import sys

import formulas
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_workbook as bw  # noqa: E402

sys.stdout.reconfigure(encoding="utf-8")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TMP = os.path.join(ROOT, "build", "_verify.xlsx")

# 8 spells spanning the level-4/5 DT boundary and the max-spell-level cutoff.
SPELLS = [
    {"Level": "1", "Name": "Magic Missile",  "School": "Evocation",     "Source": "PHB 2024", "Restriction": ""},
    {"Level": "1", "Name": "Shield",         "School": "Abjuration",    "Source": "PHB 2024", "Restriction": ""},
    {"Level": "2", "Name": "Misty Step",     "School": "Conjuration",   "Source": "PHB 2024", "Restriction": ""},
    {"Level": "2", "Name": "Web",            "School": "Conjuration",   "Source": "PHB 2024", "Restriction": ""},
    {"Level": "3", "Name": "Fireball",       "School": "Evocation",     "Source": "PHB 2024", "Restriction": ""},
    {"Level": "4", "Name": "Polymorph",      "School": "Transmutation", "Source": "PHB 2024", "Restriction": ""},
    {"Level": "5", "Name": "Wall of Force",  "School": "Evocation",     "Source": "PHB 2024", "Restriction": ""},
    {"Level": "9", "Name": "Wish",           "School": "Conjuration",   "Source": "PHB 2024", "Restriction": ""},
]
N_WIZ = 3

# character, player, wizlevel, table, subclass, contact, {level: "spells"}
WIZARDS = [
    ("Aria",  "Rob",  3,  "3", "Evoker",           "aria#1",
     {1: "Magic Missile, Shield", 2: "Misty Step"}),
    ("Bexley", "Sam", 9,  "7", "Order of Scribes", "bex#2",
     {1: "Shield", 2: "Misty Step, Web", 3: "Fireball", 4: "Polymorph",
      5: "Wall of Force"}),
    ("Cirilla", "Jo", 17, "1", "Diviner",          "ciri#3",
     {1: "Magic Missile", 3: "Fireball", 9: "Wish"}),
]


def seed():
    bw.build(spells=SPELLS, n_wiz=N_WIZ, out=TMP)
    wb = load_workbook(TMP)
    fr = wb[bw.RESP_TAB]
    for i, (char, player, lvl, table, sub, contact, books) in enumerate(WIZARDS):
        r = 2 + i
        fr.cell(row=r, column=1, value="2026-09-03")
        fr.cell(row=r, column=2, value="%s@example.test" % player.lower())
        fr.cell(row=r, column=3, value=player)
        fr.cell(row=r, column=4, value=char)
        fr.cell(row=r, column=5, value=lvl)
        fr.cell(row=r, column=6, value=table)
        fr.cell(row=r, column=7, value=sub)
        fr.cell(row=r, column=8, value=contact)
        for lv in range(1, 10):
            fr.cell(row=r, column=8 + lv, value=books.get(lv, ""))
        fr.cell(row=r, column=18, value="")
    # Aria selected; want Web (L2) and Fireball (L3) -- but Fireball is above
    # her max spell level, so only Web should be legal. Also tick Misty Step,
    # which she already owns, to prove OWNED is reported.
    cp = wb["Copy Planner"]
    cp["B1"] = "Aria"
    top = bw.PLAN_TOP
    names = [s["Name"] for s in SPELLS]
    for want in ("Web",):
        cp.cell(row=top + names.index(want), column=9, value=True)
    wb.save(TMP)


def main():
    seed()
    print("Evaluating %s ..." % os.path.basename(TMP))
    xl = formulas.ExcelModel().loads(TMP).finish()
    sol = xl.calculate()

    base = "'[%s]" % os.path.basename(TMP)

    def val(sheet, cell):
        key = "%s%s'!%s" % (base, sheet.upper(), cell)
        v = sol[key]
        try:
            v = v.value[0, 0]
        except Exception:
            pass
        return v

    failures = []

    def tidy(s):
        """Collapse the stray delimiters the offline evaluator leaves in TEXTJOIN.

        Excel and Google Sheets both drop formula-returned "" when TEXTJOIN's
        ignore_empty argument is TRUE; the `formulas` library joins them anyway,
        yielding ", , , Web, , ,". That is an evaluator limitation, not a defect
        in the workbook -- but it does mean the Owners and 'Which spells' columns
        must be eyeballed once in Google Sheets. SETUP.md lists that check.
        """
        parts = [p.strip() for p in str(s).split(",")]
        return ", ".join(p for p in parts if p)

    def check(label, got, want, textjoin=False):
        got_s = tidy(got) if textjoin else str(got).strip()
        want_s = str(want).strip()
        ok = got_s == want_s
        if not ok:  # tolerate 2.0 vs 2 from the evaluator's float arithmetic
            try:
                ok = abs(float(got) - float(want)) < 1e-9
            except (TypeError, ValueError):
                pass
        print("  %-52s %-14s %s" % (label, got_s, "ok" if ok else "EXPECTED " + want_s))
        if not ok:
            failures.append(label)

    # ---- regression: references to the response tab must survive inserts ----
    # Google Forms INSERTS a row per submission, which rewrites any direct
    # reference like 'Form Responses 1'!D2 into D3, D4, D5... This shipped
    # broken once: after three test responses every reference had drifted by
    # exactly three rows and the whole workbook read blank. Whole-column INDEX
    # is immune, so assert no direct row reference survives anywhere.
    print("\nResponse-tab references are insertion-safe")
    check_wb = load_workbook(TMP)
    bad = []
    tab = re.escape(bw.RESP_TAB)
    # The SAFE form is a bounded range inside INDEX: 'tab'!$D$1:$D$200. Strip
    # those out first, or they match the "direct reference" pattern themselves.
    safe = re.compile(r"'%s'!\$[A-R]\$1:\$[A-R]\$%d" % (tab, bw.RESP_LAST))
    direct = re.compile(r"'%s'!\$?[A-R]\$?\d" % tab)
    for sheet in check_wb.worksheets:
        for row in sheet.iter_rows():
            for cell in row:
                v = cell.value
                if isinstance(v, str) and direct.search(safe.sub("", v)):
                    bad.append("%s!%s" % (sheet.title, cell.coordinate))
    check("no direct row refs to the response tab", len(bad), 0)
    if bad:
        print("      first offenders:", ", ".join(bad[:5]))

    print("\nWizards tab -- max spell level = MIN(9, roundup(level/2))")
    check("Aria (wizard 3) max spell level", val("Wizards", "D2"), 2)
    check("Bexley (wizard 9) max spell level", val("Wizards", "D3"), 5)
    check("Cirilla (wizard 17) max spell level", val("Wizards", "D4"), 9)
    check("Bexley flagged Order of Scribes", val("Wizards", "G3"), "Yes")
    check("Aria not flagged Order of Scribes", val("Wizards", "G2"), "No")
    check("Aria spells in book", val("Wizards", "I2"), 3)
    check("Bexley spells in book", val("Wizards", "I3"), 6)
    # "Rare spells held" = spells this wizard has that nobody else does.
    #   Aria     -- Magic Missile, Shield, Misty Step are all shared  -> 0
    #   Bexley   -- Web, Polymorph, Wall of Force are his alone       -> 3
    #   Cirilla  -- Wish is hers alone                                -> 1
    check("Aria holds 0 unique spells", val("Wizards", "J2"), 0)
    check("Bexley holds 3 unique spells", val("Wizards", "J3"), 3)
    check("Cirilla holds 1 unique spell", val("Wizards", "J4"), 1)

    # Matrix layout: 3 label columns, N_WIZ name columns, N_WIZ hidden helper
    # columns, then Owners and # Owners. Those land on AB/AC only when the
    # roster is the shipped 24 -- compute them instead of hardcoding.
    own = get_column_letter(3 + N_WIZ * 2 + 1)
    cnt = get_column_letter(3 + N_WIZ * 2 + 2)
    print("\nMatrix -- presence detection (Owners=%s, #Owners=%s)" % (own, cnt))
    # rows: 2 Magic Missile, 3 Shield, 4 Misty Step, 5 Web, 6 Fireball,
    #       7 Polymorph, 8 Wall of Force, 9 Wish
    check("Aria has Magic Missile", val("Matrix", "D2"), 1)
    check("Aria has no Web", val("Matrix", "D5"), "")
    check("Bexley has Web", val("Matrix", "E5"), 1)
    check("Wish owned by exactly 1", val("Matrix", cnt + "9"), 1)
    check("Shield owned by exactly 2", val("Matrix", cnt + "3"), 2)
    check("Owners of Fireball", val("Matrix", own + "6"), "Bexley, Cirilla", textjoin=True)

    print("\nCopy Planner -- status for Aria (level 3, max spell level 2)")
    top = bw.PLAN_TOP
    check("Magic Missile (she owns it)", val("Copy Planner", "E%d" % top), "OWNED")
    check("Web (L2, Bexley has it)", val("Copy Planner", "E%d" % (top + 3)), "CAN COPY")
    check("Fireball (L3, above her level)", val("Copy Planner", "E%d" % (top + 4)), "TOO HIGH")
    check("Wish (L9, above her level)", val("Copy Planner", "E%d" % (top + 7)), "TOO HIGH")

    print("\nCopy Planner -- costs (plan: two L2 spells = 200 GP / 2 DT)")
    check("Web GP", val("Copy Planner", "G%d" % (top + 3)), 100)
    check("Web DT", val("Copy Planner", "H%d" % (top + 3)), 1)
    check("Wall of Force DT (L5 -> 2)", val("Copy Planner", "H%d" % (top + 6)), 2)
    check("Selected count", val("Copy Planner", "D2"), 1)
    check("Total GP (Web only)", val("Copy Planner", "E2"), 100)
    check("Total DT (Web only)", val("Copy Planner", "F2"), 1)
    check("DT remaining (10 - 1)", val("Copy Planner", "G2"), 9)

    # Copy Log is per SPELL, not per lender. Gold and downtime are expended by
    # the copier, so a table addressed to each lender was the wrong model: what
    # the player needs is a record of what they bought and who from. Rows from 9.
    print("\nCopy Log -- one row per spell YOU copy")
    check("row 1 spell", val("Copy Log", "B12"), "Web")
    check("row 1 level", val("Copy Log", "C12"), 2)
    check("row 1 GP", val("Copy Log", "D12"), 100)
    check("row 1 from character", val("Copy Log", "E12"), "Bexley", textjoin=True)
    check("row 1 from player", val("Copy Log", "F12"), "Sam", textjoin=True)
    check("row 2 blank (only one spell ticked)", val("Copy Log", "B13"), "")
    check("summary Total GP", val("Copy Log", "D5"), 100)
    check("summary Total DT", val("Copy Log", "E5"), 1)
    # Unused rows must contribute NOTHING to the log entry. Guarding on a
    # numeric column instead of the index built stray " (from )" fragments,
    # which TEXTJOIN then quite correctly kept.
    check("unused row 13 fragment is empty", val("Copy Log", "H13"), "")
    # The log entry nests TEXTJOIN inside TEXTJOIN, so the offline evaluator's
    # refusal to drop empty strings shows up twice over. Assert the PARTS are
    # present; exact spacing is confirmed in Sheets by TESTPLAN step 6.
    log = str(val("Copy Log", "A9"))
    print("  log entry (raw): %s" % log[:100])
    print("  log entry (tidied): %s" % tidy(log)[:100])
    for token in ("Copied 1", "Web", "L2", "100 GP", "Bexley", "Total:", "1 DT"):
        check("log entry mentions %r" % token, token in log, True)
    check("banner labels the copy cell", "PASTE THIS ONE CELL" in
          str(val("Copy Log", "A8")), True)

    # ---- second scenario: Order of Scribes changes only the DT rate ----
    # ALPG p.2: ten level 1-4 spells, or five level 5-9 spells, per 1 DT.
    # Bexley is Order of Scribes and level 9 (max spell level 5).
    wb = load_workbook(TMP)
    cp = wb["Copy Planner"]
    cp["B1"] = "Cirilla"          # a non-Scribes wizard, for the contrast
    names = [s["Name"] for s in SPELLS]
    for nm in ("Shield", "Misty Step", "Web", "Polymorph"):
        cp.cell(row=top + names.index(nm), column=9, value=True)
    wb.save(TMP)
    sol2 = formulas.ExcelModel().loads(TMP).finish().calculate()

    def val2(sheet, cell):
        v = sol2["%s%s'!%s" % (base, sheet.upper(), cell)]
        try:
            v = v.value[0, 0]
        except Exception:
            pass
        return v

    print("\nOrder of Scribes -- DT rate (4 spells of level 1-4 selected)")
    check("Cirilla (normal rate) DT = 4", val2("Copy Planner", "F2"), 4)
    check("Cirilla GP = 50+100+100+200", val2("Copy Planner", "E2"), 450)

    wb = load_workbook(TMP)
    wb["Copy Planner"]["B1"] = "Bexley"   # Order of Scribes
    wb.save(TMP)
    sol2 = formulas.ExcelModel().loads(TMP).finish().calculate()
    check("Bexley (Scribes) same 4 spells DT = 1", val2("Copy Planner", "F2"), 1)
    check("Bexley GP unchanged at 450", val2("Copy Planner", "E2"), 450)

    print("\n%s" % ("ALL CHECKS PASSED" if not failures
                    else "FAILED: %s" % ", ".join(failures)))
    return 1 if failures else 0


if __name__ == "__main__":
    try:
        code = main()
    finally:
        # Don't leave the scratch workbook in build/ -- it is not a deliverable.
        if os.path.exists(TMP):
            os.remove(TMP)
    sys.exit(code)
