"""Verify the workbook's formulas actually compute the right answers.

Builds a SMALL workbook with the identical formula patterns (same builder code,
fewer spells and wizards), seeds Form Responses with known data, evaluates every
formula with the `formulas` library, and asserts the cases named in the plan.

Small on purpose: the real workbook is ~30k formula cells, which the evaluator
would take a very long time to chew through. The formulas are generated by the
same code, so the patterns under test are the shipped patterns.
"""
import os
import re
import sys

import formulas
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_workbook as bw  # noqa: E402

sys.stdout.reconfigure(encoding="utf-8")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TMP = os.path.join(ROOT, "build", "_verify.xlsx")

# 8 spells spanning the level-4/5 DT boundary and the max-spell-level cutoff.
SPELLS = [
    {"Level": "1", "Name": "Magic Missile",  "School": "Evocation",     "Source": "PHB 2024", "Restriction": ""},
    {"Level": "1", "Name": "Shield",         "School": "Abjuration",    "Source": "PHB 2024", "Restriction": ""},
    {"Level": "2", "Name": "Misty Step",     "School": "Conjuration",   "Source": "PHB 2024", "Restriction": ""},
    {"Level": "2", "Name": "Web",            "School": "Conjuration",   "Source": "PHB 2024", "Restriction": ""},
    {"Level": "3", "Name": "Fireball",       "School": "Evocation",     "Source": "PHB 2024", "Restriction": ""},
    {"Level": "4", "Name": "Polymorph",      "School": "Transmutation", "Source": "PHB 2024", "Restriction": ""},
    {"Level": "5", "Name": "Wall of Force",  "School": "Evocation",     "Source": "PHB 2024", "Restriction": ""},
    {"Level": "9", "Name": "Wish",           "School": "Conjuration",   "Source": "PHB 2024", "Restriction": ""},
]
N_WIZ = 3

# character, player, wizlevel, table, subclass, contact, {level: "spells"}
WIZARDS = [
    ("Aria",  "Rob",  3,  "3", "Evoker",           "aria#1",
     {1: "Magic Missile, Shield", 2: "Misty Step"}),
    ("Bexley", "Sam", 9,  "7", "Order of Scribes", "bex#2",
     {1: "Shield", 2: "Misty Step, Web", 3: "Fireball", 4: "Polymorph",
      5: "Wall of Force"}),
    ("Cirilla", "Jo", 17, "1", "Diviner",          "ciri#3",
     {1: "Magic Missile", 3: "Fireball", 9: "Wish"}),
]


def seed():
    bw.build(spells=SPELLS, n_wiz=N_WIZ, out=TMP)
    wb = load_workbook(TMP)
    fr = wb[bw.RESP_TAB]
    for i, (char, player, lvl, table, sub, contact, books) in enumerate(WIZARDS):
        r = 2 + i
        fr.cell(row=r, column=1, value="2026-09-03")
        fr.cell(row=r, column=2, value="%s@example.test" % player.lower())
        fr.cell(row=r, column=3, value=player)
        fr.cell(row=r, column=4, value=char)
        fr.cell(row=r, column=5, value=lvl)
        fr.cell(row=r, column=6, value=table)
        fr.cell(row=r, column=7, value=sub)
        fr.cell(row=r, column=8, value=contact)
        for lv in range(1, 10):
            fr.cell(row=r, column=8 + lv, value=books.get(lv, ""))
        fr.cell(row=r, column=18, value="")
    # Aria selected; want Web (L2) and Fireball (L3) -- but Fireball is above
    # her max spell level, so only Web should be legal. Also tick Misty Step,
    # which she already owns, to prove OWNED is reported.
    cp = wb["Copy Planner"]
    cp["B1"] = "Aria"
    top = bw.PLAN_TOP
    names = [s["Name"] for s in SPELLS]
    for want in ("Web",):
        cp.cell(row=top + names.index(want), column=9, value=True)
    wb.save(TMP)


def main():
    seed()
    print("Evaluating %s ..." % os.path.basename(TMP))
    xl = formulas.ExcelModel().loads(TMP).finish()
    sol = xl.calculate()

    base = "'[%s]" % os.path.basename(TMP)

    def val(sheet, cell):
        key = "%s%s'!%s" % (base, sheet.upper(), cell)
        v = sol[key]
        try:
            v = v.value[0, 0]
        except Exception:
            pass
        return v

    failures = []

    def check(label, got, want):
        got_s = str(got).strip()
        want_s = str(want).strip()
        ok = got_s == want_s
        if not ok:  # tolerate 2.0 vs 2 from the evaluator's float arithmetic
            try:
                ok = abs(float(got) - float(want)) < 1e-9
            except (TypeError, ValueError):
                pass
        print("  %-52s %-14s %s" % (label, got_s, "ok" if ok else "EXPECTED " + want_s))
        if not ok:
            failures.append(label)

    # ---- regression: references to the response tab must survive inserts ----
    # Google Forms INSERTS a row per submission, which rewrites any direct
    # reference like 'Form Responses 1'!D2 into D3, D4, D5... This shipped
    # broken once: after three test responses every reference had drifted by
    # exactly three rows and the whole workbook read blank. Whole-column INDEX
    # is immune, so assert no direct row reference survives anywhere.
    print("\nResponse-tab references are insertion-safe")
    check_wb = load_workbook(TMP)
    bad = []
    tab = re.escape(bw.RESP_TAB)
    # The SAFE form is a bounded range inside INDEX: 'tab'!$D$1:$D$200. Strip
    # those out first, or they match the "direct reference" pattern themselves.
    safe = re.compile(r"'%s'!\$[A-R]\$1:\$[A-R]\$%d" % (tab, bw.RESP_LAST))
    direct = re.compile(r"'%s'!\$?[A-R]\$?\d" % tab)
    for sheet in check_wb.worksheets:
        for row in sheet.iter_rows():
            for cell in row:
                v = cell.value
                if isinstance(v, str) and direct.search(safe.sub("", v)):
                    bad.append("%s!%s" % (sheet.title, cell.coordinate))
    check("no direct row refs to the response tab", len(bad), 0)
    if bad:
        print("      first offenders:", ", ".join(bad[:5]))

    # ---- regression: only functions both Sheets and Excel 2007+ have ----
    # TEXTJOIN shipped once: Excel 2016 lacks it, and Google's .xlsx export
    # drops the _xlfn. prefix newer Excel expects, so a copy downloaded from
    # Sheets showed #NAME? down the whole Matrix Owners column. An allowlist
    # rather than a list of known-bad names, so the NEXT such function fails
    # here too. Adding to it means checking the function exists in Google
    # Sheets AND in Excel 2007 -- not just in whatever Excel is to hand.
    print("\nFormulas use only functions Sheets and Excel 2007+ share")
    allowed = {"AND", "CEILING", "COUNT", "COUNTIF", "COUNTIFS", "IF", "IFERROR",
               "INDEX", "ISNUMBER", "MATCH", "MID", "MIN", "OR", "SEARCH",
               "SMALL", "SUMIF"}
    literal = re.compile(r'"(?:[^"]|"")*"')     # skip text like " (L2, ..."
    call = re.compile(r"\b([A-Z][A-Z0-9._]*)\(")
    late = {}
    for sheet in check_wb.worksheets:
        for row in sheet.iter_rows():
            for cell in row:
                v = cell.value
                if isinstance(v, str) and v.startswith("="):
                    for fn in set(call.findall(literal.sub('""', v))) - allowed:
                        late.setdefault(fn, "%s!%s" % (sheet.title, cell.coordinate))
    check("no function outside the allowlist", len(late), 0)
    for fn, where in sorted(late.items()):
        print("      %s, first at %s" % (fn, where))

    print("\nWizards tab -- max spell level = MIN(9, roundup(level/2))")
    check("Aria (wizard 3) max spell level", val("Wizards", "D2"), 2)
    check("Bexley (wizard 9) max spell level", val("Wizards", "D3"), 5)
    check("Cirilla (wizard 17) max spell level", val("Wizards", "D4"), 9)
    check("Bexley flagged Order of Scribes", val("Wizards", "G3"), "Yes")
    check("Aria not flagged Order of Scribes", val("Wizards", "G2"), "No")
    check("Aria spells in book", val("Wizards", "I2"), 3)
    check("Bexley spells in book", val("Wizards", "I3"), 6)
    # "Rare spells held" = spells this wizard has that nobody else does.
    #   Aria     -- Magic Missile, Shield, Misty Step are all shared  -> 0
    #   Bexley   -- Web, Polymorph, Wall of Force are his alone       -> 3
    #   Cirilla  -- Wish is hers alone                                -> 1
    check("Aria holds 0 unique spells", val("Wizards", "J2"), 0)
    check("Bexley holds 3 unique spells", val("Wizards", "J3"), 3)
    check("Cirilla holds 1 unique spell", val("Wizards", "J4"), 1)

    # Matrix layout: 3 label columns, N_WIZ name columns, N_WIZ hidden helper
    # columns, then Owners and # Owners. Those land on AB/AC only when the
    # roster is the shipped 24 -- compute them instead of hardcoding.
    own = get_column_letter(3 + N_WIZ * 2 + 1)
    cnt = get_column_letter(3 + N_WIZ * 2 + 2)
    print("\nMatrix -- presence detection (Owners=%s, #Owners=%s)" % (own, cnt))
    # rows: 2 Magic Missile, 3 Shield, 4 Misty Step, 5 Web, 6 Fireball,
    #       7 Polymorph, 8 Wall of Force, 9 Wish
    check("Aria has Magic Missile", val("Matrix", "D2"), 1)
    check("Aria has no Web", val("Matrix", "D5"), "")
    check("Bexley has Web", val("Matrix", "E5"), 1)
    check("Wish owned by exactly 1", val("Matrix", cnt + "9"), 1)
    check("Shield owned by exactly 2", val("Matrix", cnt + "3"), 2)
    check("Owners of Fireball", val("Matrix", own + "6"), "Bexley, Cirilla")
    check("Owners of Wish", val("Matrix", own + "9"), "Cirilla")

    print("\nCopy Planner -- status for Aria (level 3, max spell level 2)")
    top = bw.PLAN_TOP
    check("Magic Missile (she owns it)", val("Copy Planner", "E%d" % top), "OWNED")
    check("Web (L2, Bexley has it)", val("Copy Planner", "E%d" % (top + 3)), "CAN COPY")
    check("Fireball (L3, above her level)", val("Copy Planner", "E%d" % (top + 4)), "TOO HIGH")
    check("Wish (L9, above her level)", val("Copy Planner", "E%d" % (top + 7)), "TOO HIGH")

    print("\nCopy Planner -- costs (plan: two L2 spells = 200 GP / 2 DT)")
    check("Web GP", val("Copy Planner", "G%d" % (top + 3)), 100)
    check("Web DT", val("Copy Planner", "H%d" % (top + 3)), 1)
    check("Wall of Force DT (L5 -> 2)", val("Copy Planner", "H%d" % (top + 6)), 2)
    check("Selected count", val("Copy Planner", bw.CP_COUNT), 1)
    check("Total GP (Web only)", val("Copy Planner", bw.CP_GP_TOTAL), 100)
    check("Total DT (Web only)", val("Copy Planner", bw.CP_DT_TOTAL), 1)
    check("DT left (10 - 1)", val("Copy Planner", bw.CP_DT_LEFT), 9)
    check("DT within budget", val("Copy Planner", bw.CP_DT_STATUS), "WITHIN BUDGET")
    # Gold starts blank: no comparison is made until the player enters a total.
    check("GP left blank with no gold entered", val("Copy Planner", bw.CP_GP_LEFT), "")
    check("GP status asks for a total",
          "enter your total" in str(val("Copy Planner", bw.CP_GP_STATUS)), True)

    # Copy Log is per SPELL, not per lender. Gold and downtime are expended by
    # the copier, so a table addressed to each lender was the wrong model: what
    # the player needs is a record of what they bought and who from. Rows from 9.
    print("\nCopy Log -- one row per spell YOU copy")
    check("row 1 spell", val("Copy Log", "B12"), "Web")
    check("row 1 level", val("Copy Log", "C12"), 2)
    check("row 1 GP", val("Copy Log", "D12"), 100)
    check("row 1 from character", val("Copy Log", "E12"), "Bexley")
    check("row 1 from player", val("Copy Log", "F12"), "Sam")
    check("row 2 blank (only one spell ticked)", val("Copy Log", "B13"), "")
    check("summary Total GP", val("Copy Log", "D5"), 100)
    check("summary Total DT", val("Copy Log", "E5"), 1)
    # Unused rows must contribute NOTHING to the log entry. Guarding on a
    # numeric column instead of the index built stray " (from )" fragments.
    check("unused row 13 fragment is empty", val("Copy Log", "H13"), "")
    check("log entry, exactly", val("Copy Log", "A9"),
          "Copied 1 wizard spell(s) into spellbook: Web (L2, 100 GP) from Bexley. "
          "Total: 100 GP and 1 DT.")
    check("banner labels the copy cell", "PASTE THIS ONE CELL" in
          str(val("Copy Log", "A8")), True)

    # ---- second scenario: Order of Scribes changes only the DT rate ----
    # ALPG p.2: ten level 1-4 spells, or five level 5-9 spells, per 1 DT.
    # Bexley is Order of Scribes and level 9 (max spell level 5).
    wb = load_workbook(TMP)
    cp = wb["Copy Planner"]
    cp["B1"] = "Cirilla"          # a non-Scribes wizard, for the contrast
    names = [s["Name"] for s in SPELLS]
    for nm in ("Shield", "Misty Step", "Web", "Polymorph"):
        cp.cell(row=top + names.index(nm), column=9, value=True)
    # Budgets below the 450 GP / 4 DT these four cost, to trip both flags.
    cp[bw.CP_GP_BUDGET] = 400
    cp[bw.CP_DT_BUDGET] = 3
    wb.save(TMP)
    sol2 = formulas.ExcelModel().loads(TMP).finish().calculate()

    def val2(sheet, cell):
        v = sol2["%s%s'!%s" % (base, sheet.upper(), cell)]
        try:
            v = v.value[0, 0]
        except Exception:
            pass
        return v

    print("\nOrder of Scribes -- DT rate (4 spells of level 1-4 selected)")
    check("Cirilla (normal rate) DT = 4", val2("Copy Planner", bw.CP_DT_TOTAL), 4)
    check("Cirilla GP = 50+100+100+200", val2("Copy Planner", bw.CP_GP_TOTAL), 450)

    # Several spells, several owners: both separators, with no stray ones from
    # the 36 unused log rows or the wizards who don't hold a given spell.
    print("\nCopy Log -- four spells, joined exactly")
    check("Shield from two players", val2("Copy Log", "F12"), "Rob, Sam")
    check("log entry, exactly", val2("Copy Log", "A9"),
          "Copied 4 wizard spell(s) into spellbook: "
          "Shield (L1, 50 GP) from Aria, Bexley; "
          "Misty Step (L2, 100 GP) from Aria, Bexley; "
          "Web (L2, 100 GP) from Bexley; "
          "Polymorph (L4, 200 GP) from Bexley. "
          "Total: 450 GP and 4 DT.")

    print("\nBudgets -- 400 GP and 3 DT against Cirilla's 450 GP / 4 DT")
    check("GP left 400 - 450", val2("Copy Planner", bw.CP_GP_LEFT), -50)
    check("GP over budget", val2("Copy Planner", bw.CP_GP_STATUS), "OVER BUDGET")
    check("DT left 3 - 4", val2("Copy Planner", bw.CP_DT_LEFT), -1)
    check("DT over budget", val2("Copy Planner", bw.CP_DT_STATUS), "OVER BUDGET")

    wb = load_workbook(TMP)
    wb["Copy Planner"]["B1"] = "Bexley"   # Order of Scribes
    wb.save(TMP)
    sol2 = formulas.ExcelModel().loads(TMP).finish().calculate()
    check("Bexley (Scribes) same 4 spells DT = 1", val2("Copy Planner", bw.CP_DT_TOTAL), 1)
    check("Bexley GP unchanged at 450", val2("Copy Planner", bw.CP_GP_TOTAL), 450)
    # Same budgets: the Scribes rate brings downtime in under, gold stays over.
    # The two flags are independent -- neither resource is assumed to bind.
    check("Bexley DT within budget (1 of 3)", val2("Copy Planner", bw.CP_DT_STATUS),
          "WITHIN BUDGET")
    check("Bexley GP still over budget", val2("Copy Planner", bw.CP_GP_STATUS),
          "OVER BUDGET")

    # ---- third scenario: levelling up at the end of the Epic ----
    # Aria registered at wizard level 3 (max spell level 2). Entering 5 in B3
    # must open level 3 spells to her without touching what she registered.
    def plan_as_aria(new_level):
        wb = load_workbook(TMP)
        cp = wb["Copy Planner"]
        cp["B1"] = "Aria"
        cp[bw.CP_NEW_LEVEL] = new_level
        wb.save(TMP)
        sol = formulas.ExcelModel().loads(TMP).finish().calculate()

        def v(sheet, cell):
            x = sol["%s%s'!%s" % (base, sheet.upper(), cell)]
            try:
                x = x.value[0, 0]
            except Exception:
                pass
            return x
        return v

    print("\nLevelling up -- Aria (registered wizard 3) enters new level 5")
    v = plan_as_aria(5)
    check("max spell level now 3", v("Copy Planner", bw.CP_MAXLVL), 3)
    check("Fireball (L3) now CAN COPY", v("Copy Planner", "E%d" % (top + 4)), "CAN COPY")
    check("Wall of Force (L5) still TOO HIGH", v("Copy Planner", "E%d" % (top + 6)), "TOO HIGH")
    check("Wizards tab keeps registered max level 2", v("Wizards", "D2"), 2)
    check("note shows registered level and new reach",
          "level 3, copying up to spell level 3" in str(v("Copy Planner", bw.CP_LEVEL_NOTE)),
          True)

    # Levels are never lost, so a lower entry must not shrink what she can copy.
    print("\nLevelling up -- a LOWER level is ignored, not trusted")
    v = plan_as_aria(1)
    check("max spell level stays 2", v("Copy Planner", bw.CP_MAXLVL), 2)
    check("Web (L2) still CAN COPY", v("Copy Planner", "E%d" % (top + 3)), "CAN COPY")

    print("\n%s" % ("ALL CHECKS PASSED" if not failures
                    else "FAILED: %s" % ", ".join(failures)))
    return 1 if failures else 0


if __name__ == "__main__":
    try:
        code = main()
    finally:
        # Don't leave the scratch workbook in build/ -- it is not a deliverable.
        if os.path.exists(TMP):
            os.remove(TMP)
    sys.exit(code)
